name: a BOT Report
description: File a BOT report
title: "[Bot]: "
labels: [bot]

body:
  - type: markdown
    attributes:
      value: |
        Are you a BOT?
  - type: input
    id: username
    attributes:
      label: BOT NAME
      description: user bot name
      placeholder: yes i am a bot
    validations:
      required: false
  - type: textarea
    id: robotworld
    attributes:
      label: verify
      description: give example
      placeholder: why is a bot ruining us?
      value: "a bot infestation"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: real or not?
      options:
        - BOT
        - user
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What system are you seeing the bot on?
      multiple: true
      options:
        - TWITCH
        - Mobile APP
        - Chatty
        - Chatterino
        - Botlist
        - Other
  - type: textarea
    id: logs
    attributes:
      label: log output
      description: post log
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: CODE
      description: are you human?
      options:
        - label: i am human
          required: true
